Repository myhandJAVA/be09-2nd-myHandJava-momentours, pull requests merged in 2024-09, with the labels that each got.

#34 feat: 일정 삭제 기능 추가
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/aggregate/Schedule.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#36 feat: 일기 수정 기능 추가
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/aggregate/Diary.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/dto/FileDTO.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/aggregate/FileBoardSort.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/aggregate/FileEntity.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/repository/FileRepository.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#38 refactor: 일기 조회 기능 구조 개선
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/dto/FileDTO.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/repository/FileMapper.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/main/resources/mappers/file/FileMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#41 refactor: 일기 등록 기능 구조 개선
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#44 feat: 추억 조회 기능
  momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/dto/MomentDTO.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/aggregate/Moment.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/aggregate/MomentCategory.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/aggregate/MomentCategoryConverter.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/repository/MomentRepository.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/vo/ResponseFindMomentByCoupleNoVO.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/vo/ResponseFindMomentByMomentPublicVO.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/dto/MomentCategory.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/dto/MomentDTO.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/repository/MomentMapper.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/service/MomentServiceImpl.java
  momentours/src/main/resources/mappers/moment/MomentMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/moment/query/service/MomentServiceImplTests.java
Labels: feat✨, BackEnd🔙

#46 feat. 예정 코스 조회
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/repository/MomentCourseMapper.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/dto/TodoCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/repository/TodoCourseMapper.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImpl.java
  momentours/src/main/resources/mappers/todocourse/TodoCourseMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#47 feat: 랜덤질문 답변 내용 수정 및 삭제
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/dto/RandomQuestionDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/dto/RandomReplyDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/Repository/RandomQuestionRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/Repository/RandomReplyRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/aggregate/RandomQuestion.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/aggregate/RandomReply.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/vo/ModifyReplyVO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceImpl.java
  momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml
  momentours/src/main/resources/mappers/randomquestion/RandomReplyMapper.xml
Labels: feat✨, BackEnd🔙

#50 refactor: 일기 삭제 기능 구조 개선
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/aggregate/FileBoardSort.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/aggregate/FileEntity.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/domain/repository/FileRepository.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/dto/FileDTO.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/repository/FileMapper.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/main/resources/mappers/file/FileMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#52 refactor: 일정 기능 구조 개선
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
Labels: refactor✂️, BackEnd🔙

#53 feat: 일기 댓글 조회
  momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/CommentDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#58 feat: 일기 댓글 등록 기능 개발
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/CommentController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/dto/CommentDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/aggregate/Comment.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/CommentRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistCommentVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/CommentDTO.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImplTests.java
Labels: feat✨, BackEnd🔙

#60 feat: 일기 댓글 삭제 기능 개발
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/CommentController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/CommentRepository.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/CommentServiceImplTests.java
Labels: feat✨, BackEnd🔙

#66 feat: 일기 전체 조회 기능 추가
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/repository/DiaryMapper.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#67 feat: 커플별 고유 랜덤질문 생성 기능 개발
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
Labels: feat✨, fix🛠️, BackEnd🔙

#70 Revert "feat: 커플별 고유 랜덤질문 생성 기능 개발"
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
Labels: bug

#71 feat: 추억 수정
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/repository/MomentRepository.java
  momentours/src/test/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImplTests.java
Labels: feat✨, BackEnd🔙

#73 feat: 회원 msa 프로젝트 생성 및 CRUD 구현
  momentours-user/.gitignore
  momentours-user/build.gradle
  momentours-user/gradle/wrapper/gradle-wrapper.jar
  momentours-user/gradle/wrapper/gradle-wrapper.properties
  momentours-user/gradlew
  momentours-user/gradlew.bat
  momentours-user/settings.gradle
  momentours-user/src/main/java/com/myhandjava/momentoursUser/MomentoursUserApplication.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/dto/UserDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/aggregate/Gender.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/aggregate/MBTI.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/aggregate/UserEntity.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/aggregate/UserRole.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/repository/UserRepository.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestLoginVO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestRegistUserVO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestUpdateUserVO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/ResponseFindUserVO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/common/ResponseMessage.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/config/AppConfig.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/config/MybatisConfiguration.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/repository/UserMapper.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/AuthenticationFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtUtil.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours-user/src/main/resources/application.yml
  momentours-user/src/main/resources/mappers/user/UserMapper.xml
  momentours-user/src/test/java/com/myhandjava/momentoursUser/MomentoursUserApplicationTests.java
Labels: feat✨, BackEnd🔙

#77 feat: 추억 삭제
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImpl.java
Labels: feat✨, BackEnd🔙

#79 User make couple
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/dto/UserDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestCoupleVO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserServiceImpl.java
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/resources/application.yaml
Labels: feat✨, BackEnd🔙

#81 Couple select
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/aggregate/Couple.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/dto/CoupleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/repository/CoupleMapper.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/service/CoupleService.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/service/CoupleServiceImpl.java
  momentours/src/main/resources/mappers/couple/CoupleMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/couple/query/service/CoupleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#82 feat: 추억 조회수 증가 기능
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/domain/repository/MomentRepository.java
Labels: feat✨, BackEnd🔙

#83 feat
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/MomcourselocationDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/MomentCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/Momcourselocation.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/MomentCourse.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/MomentCourseSort.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/MomcourselocationRepository.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/MomentCourseRepository.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/vo/RequestRegistMomCourseVO.java
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#86 feat: 추억코스 삭제
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/MomentCourseRepository.java
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#91 feat: 추억코스 좋아요/취소 기능
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#93 feat: 추억코스 즐겨찾기/취소 기능
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/FavoriteDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/Favorite.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/FavoriteRepository.java
Labels: feat✨, BackEnd🔙

#96 refactor: 추억 코스 수정 기능 코드 수정
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
Labels: refactor✂️, BackEnd🔙

#97 예정 코스 생성
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/dto/TodoCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/aggregate/TodoCourse.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/repository/TodoCourseRepository.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestRegistTodoCourseVO.java
  momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#98 feat: 회원 번호 2개 받아서 커플 정보 입력하는 창으로 안내 후 정보를 입력하면 회원 번호 자동 set까지 구현
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/dto/CoupleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleService.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/repository/CoupleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistNumberVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
Labels: feat✨, BackEnd🔙

#100 refator: 추억 코스 즐겨찾기 코드 수정
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/dto/FavoriteDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/aggregate/Favorite.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/repository/FavoriteRepository.java
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#102 feat: 예정데이트코스 일정 조회
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/resources/application.yaml
Labels: feat✨, BackEnd🔙

#103 Couple update
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java
  momentours/src/test/java/com/myhandjava/momentours/couple/command/application/service/CoupleCommandServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/couple/query/service/CoupleQueryServiceImplTests.java
Labels: feat✨, test⚙️, BackEnd🔙

#106 예정 코스 수정
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/dto/TodoCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/dto/TodocourselocationDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/aggregate/TodoCourse.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/aggregate/Todocourselocation.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/repository/TodoCourseRepository.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/repository/TodoCourselocationRepository.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestModifyTodoCourseVO.java
  momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#108 Randomquestion create
  momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceTests.java
Labels: feat✨, BackEnd🔙

#109 feat. 예정 코스 삭제
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/main/resources/application.yaml
  momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#110 Randomquestion create
  momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java
Labels: feat✨, refactor✂️, BackEnd🔙

#113 feat. 예정 코스 좋아요 기능
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/dto/TodoCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#116 feat: 공지 작성
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/controller/NotificationController.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/dto/NotificationDTO.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/service/NotificationService.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/service/NotificationServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/aggregate/Notification.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/repository/NotificationRepository.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/domain/vo/NotificationVO.java
Labels: feat✨, BackEnd🔙

#115 feat: 추억 코스 검색 기능
  momentours/src/main/java/com/myhandjava/momentours/moment/query/dto/MomentDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/dto/MomcourselocationDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/dto/MomentCourseDTO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/repository/MomentCourseMapper.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyServiceImpl.java
  momentours/src/main/resources/mappers/momentcourse/MomentCourseMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/momentcourse/query/service/MomentCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#119 test: 추억 수정 테스트
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/test/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImplTests.java
Labels: test⚙️, BackEnd🔙

#120 test: 추억 삭제 테스트
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentService.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImpl.java
  momentours/src/main/resources/application.yaml
  momentours/src/test/java/com/myhandjava/momentours/moment/command/application/service/MomentServiceImplTests.java
Labels: test⚙️, BackEnd🔙

#122 feat. 예정 코스 검색
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/dto/TodocourselocationDTO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/repository/TodoCourseMapper.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImpl.java
  momentours/src/main/resources/mappers/todocourse/TodoCourseMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/todocourse/query/service/TodoCourseServiceImplTests.java
Labels: feat✨, BackEnd🔙

#124 feat: 토큰 정보 추가
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/dto/CoupleDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/repository/UserMapper.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/AuthenticationFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours-user/src/main/resources/mappers/user/UserMapper.xml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/config/FeignClientConfig.java
Labels: feat✨, BackEnd🔙

#126 feat: 토큰 인터셉터 추가
  momentours-user/src/main/resources/application.yml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/config/TokenInterceptor.java
  momentours/src/main/java/com/myhandjava/momentours/config/WebMvcConfig.java
Labels: feat✨, BackEnd🔙

#127 refactor: 프로젝트 코드 구조 수정
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyCommentVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistCommentVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/vo/RequestModifyMomCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/vo/RequestRegistMomCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/controller/NotificationController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
Labels: refactor✂️, BackEnd🔙

#128 refactor: 프로젝트 코드 구조 수정
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/notification/command/application/controller/NotificationController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
Labels: refactor✂️, BackEnd🔙

#129 feat: 토큰에서 claim 받아오는 필터 추가
  momentours-gateway/src/main/java/com/myhandjava/momentoursgateway/filter/AuthorizationHeaderFilter.java
  momentours-gateway/src/main/resources/application.yml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/config/FeignClientConfig.java
  momentours/src/main/java/com/myhandjava/momentours/config/SecurityConfig.java
  momentours/src/main/java/com/myhandjava/momentours/config/TokenInterceptor.java
  momentours/src/main/resources/application.yaml
  momentours/src/main/resources/mappers/momentcourse/MomentCourseMapper.xml
Labels: feat✨, BackEnd🔙

#131 feat: gateway momentours service 호출 메소드 방식 추가
  momentours-gateway/src/main/resources/application.yml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
Labels: feat✨, BackEnd🔙

#133 feat: momentours 프로젝트에 feign client 추가
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/repository/UserMapper.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserServiceImpl.java
  momentours-user/src/main/resources/mappers/user/UserMapper.xml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/client/UserClient.java
Labels: feat✨, BackEnd🔙

#136 refactor: Claims 값 받기 수정
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
Labels: refactor✂️, BackEnd🔙

#138 refactor: 일정 도메인 코드 리팩토링
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/ModifyScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/RegistScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#140 refactor: 일정 도메인 코드 리팩토링
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/ModifyScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/RegistScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#145 style: HttpStatusCode 추가 작성
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
Labels: style💡, BackEnd🔙

#149 Couple refactor
  momentours-user/src/main/java/com/myhandjava/momentoursUser/client/MomentoursClient.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/dto/CoupleDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/dto/CoupleRegisterDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserQueryService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserQueryServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/AuthenticationFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtUtil.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/dto/CoupleRegisterDTO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleService.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/command/application/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/moment/query/controller/MomentController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/Exception/RandomQuestionException.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomQuestionRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomReplyRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/vo/RegistRequestReplyVO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/ModifyScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/RegistScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
  momentours/src/test/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyQueryServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceTests.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: fix🛠️, refactor✂️, BackEnd🔙

#150 feat: 설정 서버 추가
  momentours-config/.gitignore
  momentours-config/build.gradle
  momentours-config/gradle/wrapper/gradle-wrapper.jar
  momentours-config/gradle/wrapper/gradle-wrapper.properties
  momentours-config/gradlew
  momentours-config/gradlew.bat
  momentours-config/settings.gradle
  momentours-config/src/main/java/com/myhandjava/momentoursconfig/MomentoursConfigApplication.java
  momentours-config/src/main/resources/application.yml
  momentours-config/src/test/java/com/myhandjava/momentoursconfig/MomentoursConfigApplicationTests.java
  momentours-gateway/build.gradle
  momentours-gateway/src/main/resources/application.yml
  momentours-gateway/src/main/resources/bootstrap.yml
  momentours-user/build.gradle
  momentours-user/src/main/resources/application.yml
  momentours-user/src/main/resources/bootstrap.yml
  momentours/build.gradle
  momentours/src/main/resources/application.yaml
  momentours/src/main/resources/bootstrap.yml
Labels: feat✨, BackEnd🔙

#151 refactor: HttpStatusCode 빼먹은 거 추가
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
Labels: bug, fix🛠️, BackEnd🔙

#152 refactor: 프로젝트 코드 구조 수정 및 일기 1번만 쓰기 추가
  momentours-gateway/.idea/modules/momentours-gateway.main.iml
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/repository/DiaryMapper.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#153 Couple refactor
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/Exception/RandomQuestionException.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomQuestionRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/repository/RandomReplyRepository.java
  momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml
  momentours/src/main/resources/mappers/randomquestion/RandomReplyMapper.xml
Labels: fix🛠️, refactor✂️, BackEnd🔙

#156 feat: 커플 삭제 시 다이어리 관련 데이터 삭제 기능 추가
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/CommentRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/TemporaryRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#159 Refactor: 스케줄 코드 부분 구조 개선
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/service/UserServiceImpl.java
  momentours-user/src/main/resources/application.yml
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/resources/application.yaml
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#160 refactor: 예외클래스 수정
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/service/MomentCourseServiceImpl.java
Labels: refactor✂️, BackEnd🔙

#165 refactor: 예외를 사용자 정의 예외를 던지도록 수정했습니다.
  momentours/src/main/java/com/myhandjava/momentours/common/CommonException.java
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
Labels: refactor✂️, BackEnd🔙

#168 refactor: 예외를 사용자 정의 예외를 던지도록 수정
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/repository/CoupleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
Labels: refactor✂️, BackEnd🔙

#169 refactor: 일기 파일 관련 기능
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileService.java
  momentours/src/main/java/com/myhandjava/momentours/file/command/application/service/FileServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/service/FileService.java
  momentours/src/main/java/com/myhandjava/momentours/file/query/service/FileServiceImpl.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#170 refactor: 토큰 기능 구조 수정
  momentours-config/src/main/resources/application.yml
  momentours-gateway/build/classes/java/main/com/myhandjava/momentoursgateway/filter/AuthorizationHeaderFilter$Config.class
  momentours-gateway/src/main/java/com/myhandjava/momentoursgateway/filter/AuthorizationHeaderFilter.java
  momentours-gateway/src/main/java/com/myhandjava/momentoursgateway/filter/CheckRoleFilter.java
  momentours-gateway/src/main/resources/application.yml
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/AuthenticationFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtFilter.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/JwtUtil.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/config/SecurityConfig.java
  momentours/src/main/java/com/myhandjava/momentours/config/TokenInterceptor.java
  momentours/src/main/java/com/myhandjava/momentours/config/WebMvcConfig.java
Labels: refactor✂️, BackEnd🔙

#173 refactor: 예정 코스 수정
  momentours-server/.idea/.gitignore
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseService.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestModifyTodoCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestRegistTodoCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
  momentours/src/main/resources/mappers/todocourse/TodoCourseMapper.xml
Labels: fix🛠️, refactor✂️, BackEnd🔙

#174 refactor: Body에 커플 번호를 담도록 수정
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/dto/CoupleRegisterDTO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleRegistVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java
  momentours/src/main/java/com/myhandjava/momentours/couple/query/controller/CoupleController.java
Labels: refactor✂️, BackEnd🔙

#176 Refactor: 스케줄 컨트롤러 리팩토링
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
Labels: refactor✂️, BackEnd🔙

#180 feat: 요청에 담긴 번호 유효성 검사 Service 추가
  momentours-gateway/src/main/resources/application.yml
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserQueryService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/query/service/UserQueryServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/AuthenticationFilter.java
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/client/UserClient.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/service/ScheduleValidService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/service/ScheduleValidServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/UserCoupleNoVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
Labels: feat✨, BackEnd🔙

#181 docs: Swagger와 SpringDoc를 이용해 API 문서화 자동화하기
  momentours/src/main/java/com/myhandjava/momentours/config/SwaggerConfig.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyCommentVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestModifyDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistCommentVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/application/controller/MomentCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/vo/RequestModifyMomCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/command/domain/vo/RequestRegistMomCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/momentcourse/query/controller/MomentCourseController.java
  momentours/src/main/resources/application.yaml
Labels: docs📖, feat✨, BackEnd🔙

#183 refactor: 스케줄 유효성 검사 구조 리팩토링
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/applicaiton/controller/UserController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/command/domain/vo/RequestCoupleVO.java
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/PutScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/UserCoupleNoVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/FindScheduleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/repository/ScheduleMapper.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
Labels: refactor✂️, BackEnd🔙

#185 refactor: 토큰 수정 관련 예정 코스 컨트롤러 메소드 리팩토링
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/controller/TodoCourseController.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/application/service/TodoCourseServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestModifyTodoCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/command/domain/vo/RequestRegistTodoCourseVO.java
  momentours/src/main/java/com/myhandjava/momentours/todocourse/query/controller/TodoCourseController.java
  momentours/src/main/resources/mappers/todocourse/TodoCourseMapper.xml
Labels: fix🛠️, refactor✂️, BackEnd🔙

#187 Openai refactor
  momentours-gateway/build/classes/java/main/com/myhandjava/momentoursgateway/MomentoursGatewayApplication.class
  momentours-gateway/build/classes/java/main/com/myhandjava/momentoursgateway/filter/AuthorizationHeaderFilter.class
  momentours-gateway/build/classes/java/main/com/myhandjava/momentoursgateway/filter/CheckRoleFilter$Config.class
  momentours-gateway/build/classes/java/main/com/myhandjava/momentoursgateway/filter/CheckRoleFilter.class
  momentours-gateway/build/resources/main/application.yml
  momentours-gateway/build/resources/main/bootstrap.yml
  momentours-server/build/classes/java/main/com/myhandjava/momentoursserver/MomentoursServerApplication.class
  momentours-server/build/classes/java/test/com/myhandjava/momentoursserver/MomentoursServerApplicationTests.class
  momentours/src/main/java/com/myhandjava/momentours/client/OpenAIClient.java
  momentours/src/main/java/com/myhandjava/momentours/common/HttpStatusCode.java
  momentours/src/main/java/com/myhandjava/momentours/config/FeignClientConfig.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/OpenAIServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyCommandServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/vo/ModifyReplyVO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/vo/RegistRequestReplyVO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/controller/RandomQuestionAndReplyController.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionAndReplyQueryServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionAndReplyQueryServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#189 feat: 카카오 로그인 기능 구현
  momentours-gateway/build/resources/main/application.yml
  momentours-gateway/build/resources/main/bootstrap.yml
  momentours-gateway/src/main/resources/application.yml
  momentours-server/build/classes/java/main/com/myhandjava/momentoursserver/MomentoursServerApplication.class
  momentours-server/build/classes/java/test/com/myhandjava/momentoursserver/MomentoursServerApplicationTests.class
  momentours-server/build/resources/main/application.yml
  momentours-user/src/main/java/com/myhandjava/momentoursUser/common/HttpStatusCode.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/aggregate/KakaoAccount.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/aggregate/KakaoProfile.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/client/KakaoApiClient.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/client/KakaoLoginClient.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/controller/KakaoController.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/dto/KakaoTokenRequestDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/dto/KakaoTokenResponseDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/dto/KakaoUserInfoResponseDTO.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/service/KakaoService.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/kakao/service/KakaoServiceImpl.java
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours/.gradle/8.8/checksums/checksums.lock
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
Labels: feat✨, BackEnd🔙

#191 efactor: feignClient 설정파일 관련 오류 수정
  momentours/src/main/java/com/myhandjava/momentours/client/OpenAIClient.java
  momentours/src/main/java/com/myhandjava/momentours/client/UserClient.java
  momentours/src/main/java/com/myhandjava/momentours/config/OpenAiFeignClientConfig.java
  momentours/src/main/java/com/myhandjava/momentours/config/UserFeignClientConfig.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
Labels: refactor✂️, BackEnd🔙

#192 refact: swagger를 통한 api 명세서를 작성
  momentours-config/src/main/resources/application.yml
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/controller/CoupleController.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleService.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/couple/command/domain/vo/CoupleUpdateVO.java
  momentours/src/test/java/com/myhandjava/momentours/couple/command/application/service/CoupleServiceImplTests.java
Labels: refactor✂️, BackEnd🔙

#193 feat: cors 게이트웨이 설정 추가 및 일정 조회 리팩토링
  momentours-gateway/src/main/java/com/myhandjava/momentoursgateway/config/GatewayConfig.java
  momentours-gateway/src/main/resources/application.yml
  momentours-user/src/main/java/com/myhandjava/momentoursUser/security/WebSecurity.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/service/ScheduleValidService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/service/ScheduleValidServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/vo/RegistScheduleVO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/CalendarDTO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
Labels: feat✨, BackEnd🔙
