Repository myhandJAVA/be09-2nd-myHandJava-momentours, pull requests merged in 2024-08, with the labels that each got.

#8 Revert "feat: 일정 조회 기능 추가"
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/.idea/gradle.xml
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/aggregate/Schedule.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/ScheduleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/repository/ScheduleMapper.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
  momentours/src/main/resources/application.yaml
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
  momentours/src/main/resources/mappers/testdomain/testXML.xml
  momentours/src/test/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImplTests.java
Labels: fix🛠️

#9 feat: 일정 조회 기능 추가
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/.idea/gradle.xml
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/aggregate/Schedule.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/ScheduleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/repository/ScheduleMapper.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
  momentours/src/main/resources/application.yaml
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
  momentours/src/main/resources/mappers/testdomain/testXML.xml
  momentours/src/test/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#11 feat: 일기 조회 기능 추가
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/.idea/gradle.xml
  momentours/src/main/java/com/myhandjava/momentours/diary/query/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/repository/DiaryMapper.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImpl.java
  momentours/src/main/resources/mappers/diary/DiaryMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/diary/query/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#14 Current randomQuestion 조회
  momentours/src/main/java/com/myhandjava/momentours/config/MybatisConfiguration.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/aggregate/RandomQuestion.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/dto/RandomQuestionDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/repository/RandomQuestionMapper.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/aggregate/Schedule.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/ScheduleDTO.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/repository/ScheduleMapper.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImpl.java
  momentours/src/main/resources/application.yaml
  momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
  momentours/src/main/resources/mappers/testdomain/testXML.xml
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceTests.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/query/service/ScheduleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#17 feat: 일기 등록 기능 추가
  momentours/src/main/java/com/myhandjava/momentours/config/AppConfig.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/aggregate/Diary.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/vo/RequestRegistDiaryVO.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#20 feat: 일정 등록 기능 추가
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/.idea/gradle.xml
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/aggregate/Schedule.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/domain/repository/ScheduleRepository.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/query/dto/ScheduleDTO.java
  momentours/src/main/resources/mappers/schedule/ScheduleMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#23 feat: 일정 수정 기능 추가
  momentours/.gradle/8.8/executionHistory/executionHistory.lock
  momentours/.gradle/8.8/fileHashes/fileHashes.bin
  momentours/.gradle/8.8/fileHashes/fileHashes.lock
  momentours/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  momentours/build.gradle
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/controller/ScheduleController.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleService.java
  momentours/src/main/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImpl.java
  momentours/src/test/java/com/myhandjava/momentours/schedule/command/application/service/ScheduleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#25 feat: 일기 삭제 기능 추가
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/controller/DiaryController.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/dto/DiaryDTO.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryService.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/aggregate/Diary.java
  momentours/src/main/java/com/myhandjava/momentours/diary/command/domain/repository/DiaryRepository.java
  momentours/src/test/java/com/myhandjava/momentours/diary/command/application/service/DiaryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#27 Random question select
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/aggregate/RandomQuestion.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/dto/RandomQuestionDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/repository/RandomQuestionMapper.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceImpl.java
  momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceTests.java
Labels: feat✨, BackEnd🔙

#30 feat: 랜덤질문 답변 조회
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/application/service/RandomQuestionServiceImpl.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/command/domain/aggregate/RandomReply.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/dto/RandomQuestionAndReplyDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/dto/RandomReplyDTO.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/repository/RandomReplyMapper.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionService.java
  momentours/src/main/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceImpl.java
  momentours/src/main/resources/mappers/randomquestion/RandomQuestionMapper.xml
  momentours/src/main/resources/mappers/randomquestion/RandomReplyMapper.xml
  momentours/src/test/java/com/myhandjava/momentours/randomquestion/query/service/RandomQuestionServiceTests.java
Labels: feat✨, fix🛠️, BackEnd🔙
